AWSTemplateFormatVersion: 2010-09-09
Description: SkyPress TypeORM Query API Package Test API
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  Gateway:
    Type: AWS::Serverless::HttpApi

  TestListFn:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 10
      CodeUri: ./test/dist
      Handler: index.handler
      Events:
        Gateway:
          Type: HttpApi
          Properties:
            Method: GET
            Path: /
            ApiId: !Ref Gateway
